<template>
    <v-container
    >
    <table

            class="sm12"
    >
        <tr>
            <td>调查员信息</td>
        </tr>
        <tr>
            <td>姓名:</td>
            <td>张三</td>
            <td>性别:</td>
            <td>女</td>
            <td>职业:</td>
            <td>教师</td>
            <td>年龄</td>
            <td>12</td>
            <td>居住地</td>
            <td>地球</td>
            <td>故乡</td>
            <td>银河系</td>
        </tr>
        <tr>
            <td>职业描述</td>
            <td></td>
        </tr>
        <tr>
            <td>属性</td>
        </tr>
        <tr>
            <td>力量</td>
            <td></td>
            <td>体质</td>
            <td></td>
            <td>体型</td>
            <td></td>
        </tr>
        <tr>
            <td>敏捷</td>
            <td></td>
            <td>外貌</td>
            <td></td>
            <td>智力</td>
            <td></td>
        </tr>
         <tr>
            <td>意志</td>
            <td></td>
            <td>教育</td>
            <td></td>
            <td>移动力</td>
            <td></td>
        </tr>
        <tr>
            <td>状态</td>
        </tr>
        <tr>
            <td>生命值</td>
            <td></td>
            <td>San值</td>
            <td></td>
            <td>幸运值</td>
            <td></td>
        </tr>
        <tr>
            <td>魔法值</td>
            <td></td>
            <td></td>
            <td>状态</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>技能表</td>
        </tr>
        <tr>
            <th>名称</th>
            <th>数值</th>
            <th>名称</th>
            <th>数值</th>
            <th>名称</th>
            <th>数值</th>
        </tr>
        <tr>
            <td>会计</td>
            <td>100</td>
            <td>会计</td>
            <td>100</td>
            <td>会计</td>
            <td>100</td>
        </tr>
        <tr>
            <td>资产</td>
        </tr>
        <tr>
            <td>信用评级</td>
            <td></td>
            <td>生活水平</td>
            <td></td>
            <td>现金</td>
            <td></td>
        </tr>
        <tr>
            <td>资产</td>
            <td></td>
            <td>消费水平</td>
            <td></td>
            <td>具体资产分配</td>
            <td></td>
        </tr>
        <tr>
            <td>背景故事</td>
        </tr>
        <tr>
            <td>个人描述</td>
            <td></td>
        </tr>
         <tr>
            <td>思想与信念</td>
            <td></td>
        </tr>
         <tr>
            <td>重要之人</td>
            <td></td>
        </tr>
         <tr>
            <td>意义非凡之地</td>
            <td></td>
        </tr>
         <tr>
            <td>宝贵之物</td>
            <td></td>
        </tr>
         <tr>
            <td>特质</td>
            <td></td>
        </tr>
        <tr>
            <td>背景故事</td>
            <td></td>
        </tr>
    </table>
    </v-container>
</template>

<script>
    export default {
        name: "PlayerCardSummary"
    }
</script>

<style scoped>

</style>